on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download Artifact 'build'
        uses: actions/download-artifact@master
        with:
          name: 'build'
          path: '${{ github.workspace }}/build'      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: 'ftp.gandraerialsandsatellites.co.uk'
          ftp-username: 'gandraerialsandsatellites.co.uk'
          ftp-password: '${{ secrets.FTP_PASSWORD }}'
          local-dir: 'build/'
          git-ftp-args: '--all'
